-- if dont exsist please run this
ALTER TABLE `users`
  ADD `is_adtrack` ENUM('Y','N') CHARACTER SET utf8 COLLATE utf8_general_ci
  NULL DEFAULT 'Y' AFTER `is_billing`;

ALTER TABLE `users`
   ADD `is_branding` ENUM('Y','N') CHARACTER SET utf8 COLLATE utf8_general_ci
   NULL DEFAULT 'Y' AFTER `is_adtrack`;
-- old

-- Carousel Ad settings
ALTER TABLE `v2_map_user_network` CHANGE `campaign_type` `campaign_type` ENUM('EMAIL','TEXTAD','DISPLAY','DISPLAY-RETARGET','FB-MOBILE-NEWS-FEED','FB-DESKTOP-RIGHT-COLUMN','FB-DESKTOP-NEWS-FEED','FB-PAGE-LIKE','FB-VIDEO-VIEWS','FB-VIDEO-CLICKS','APPWALL','LANDING_PAGE','IN_APP','OVERLAY_AD','FB-CAROUSEL-AD','PUSH_CLICK_TO_CALL','ABSTRACT_BANNER_LARGE','ABSTRACT_BANNER_SMALL','ABSTRACT_BANNER_LARGE_CC','ABSTRACT_BANNER_LARGE_CM','ABSTRACT_BANNER_SMALL_CM','ABSTRACT_BANNER_SMALL_CC','FB-LOCAL-AWARENESS','REAL_ESTATE_PROFESSIONAL_CAMPAIGN','RICH_MEDIA_INTERSTITIAL','FB-MOBILE-APP-INSTALLS','FB-PROMOTE-EVENT','FB-INSTAGRAM-VIDEO','FB-INSTAGRAM','DISPLAY_YAHOO','VIDEO_YAHOO','APP_INSTALL_YAHOO','FB-LEAD','DIALOG_CLICK_TO_CALL','THIRD-PARTY-AD-TRACK','YAHOO_CAROUSEL') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;

ALTER TABLE `v2_master_campaigns` CHANGE `campaign_type` `campaign_type` ENUM('EMAIL','TEXTAD','DISPLAY','DISPLAY-RETARGET','FB-MOBILE-NEWS-FEED','FB-DESKTOP-RIGHT-COLUMN','FB-DESKTOP-NEWS-FEED','FB-PAGE-LIKE','FB-VIDEO-VIEWS','FB-VIDEO-CLICKS','APPWALL','LANDING_PAGE','IN_APP','OVERLAY_AD','PUSH_CLICK_TO_CALL','ABSTRACT_BANNER_LARGE','ABSTRACT_BANNER_SMALL','ABSTRACT_BANNER_LARGE_CC','ABSTRACT_BANNER_LARGE_CM','ABSTRACT_BANNER_SMALL_CM','ABSTRACT_BANNER_SMALL_CC','FB-LOCAL-AWARENESS','REAL_ESTATE_PROFESSIONAL_CAMPAIGN','RICH_MEDIA_INTERSTITIAL','FB-MOBILE-APP-INSTALLS','FB-PROMOTE-EVENT','FB-INSTAGRAM-VIDEO','FB-INSTAGRAM','DISPLAY_YAHOO','VIDEO_YAHOO','APP_INSTALL_YAHOO','FB-CAROUSEL-AD','FB-LEAD','DIALOG_CLICK_TO_CALL','THIRD-PARTY-AD-TRACK','YAHOO_CAROUSEL') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;

ALTER TABLE `v2_ads` CHANGE `creative_type` `creative_type` enum('DISPLAY', 'TEXTAD', 'DISPLAY_FACEBOOK', 'VIDEO', 'DISPLAY_YAHOO', 'DISPLAY_AIRPUSH', 'RICH_MEDIA', 'EVENT', 'APP_INSTALL', 'VIDEO_YAHOO', 'FB-CAROUSEL-AD', 'VIDEO-CLICKS','YAHOO_CAROUSEL') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;

-- Guarantee

ALTER TABLE `users`
   ADD `is_guarantee` ENUM('Y','N') CHARACTER SET utf8 COLLATE utf8_general_ci
   NULL DEFAULT 'N' AFTER `is_adtrack`;

ALTER TABLE `users`
 ADD `is_guarantee_percentage` INT(11) NOT NULL 
		DEFAULT '2' AFTER `is_guarantee`;

ALTER TABLE `users`
 ADD `is_guarantee_upcharge` INT(11) NOT NULL 
		DEFAULT '22' AFTER `is_guarantee`;

ALTER TABLE `v2_master_campaigns` ADD `is_thru_guarantee` ENUM('N','Y') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'N' AFTER `is_lookalike_audience`;

-- user email ability

ALTER TABLE `users` ADD `user_email_ability` ENUM('N','Y') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'Y' AFTER `is_email`;

-- pp-294 copied campaigns
ALTER TABLE `v2_master_campaigns` ADD `copied` ENUM('Y','N') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT 'N' AFTER `so`;

-- 'Campaign ID from which this campaign has been copied' AFTER `copied`
ALTER TABLE `v2_master_campaigns` ADD `copied_from_id` BIGINT(20) NULL DEFAULT NULL

ALTER TABLE `v2_master_campaigns` ADD `is_io_based_retargeting` ENUM('Y','N') NULL DEFAULT 'N' AFTER `is_remarketing_io`;

--pp-276
ALTER TABLE `v2_master_campaigns` CHANGE `campaign_type` `campaign_type` ENUM('EMAIL','TEXTAD','DISPLAY','DISPLAY-RETARGET','FB-MOBILE-NEWS-FEED','FB-DESKTOP-RIGHT-COLUMN','FB-DESKTOP-NEWS-FEED','FB-PAGE-LIKE','FB-VIDEO-VIEWS','FB-VIDEO-CLICKS','APPWALL','LANDING_PAGE','IN_APP','OVERLAY_AD','PUSH_CLICK_TO_CALL','ABSTRACT_BANNER_LARGE','ABSTRACT_BANNER_SMALL','ABSTRACT_BANNER_LARGE_CC','ABSTRACT_BANNER_LARGE_CM','ABSTRACT_BANNER_SMALL_CM','ABSTRACT_BANNER_SMALL_CC','FB-LOCAL-AWARENESS','REAL_ESTATE_PROFESSIONAL_CAMPAIGN','RICH_MEDIA_INTERSTITIAL','FB-MOBILE-APP-INSTALLS','FB-PROMOTE-EVENT','FB-INSTAGRAM-VIDEO','FB-INSTAGRAM','DISPLAY_YAHOO','VIDEO_YAHOO','APP_INSTALL_YAHOO','FB-CAROUSEL-AD','FB-LEAD','DIALOG_CLICK_TO_CALL','THIRD-PARTY-AD-TRACK','YAHOO_CAROUSEL','RICH_MEDIA_SURVEY') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `v2_map_user_network` CHANGE `campaign_type` `campaign_type` ENUM('EMAIL','TEXTAD','DISPLAY','DISPLAY-RETARGET','FB-MOBILE-NEWS-FEED','FB-DESKTOP-RIGHT-COLUMN','FB-DESKTOP-NEWS-FEED','FB-PAGE-LIKE','FB-VIDEO-VIEWS','FB-VIDEO-CLICKS','APPWALL','LANDING_PAGE','IN_APP','OVERLAY_AD','FB-CAROUSEL-AD','PUSH_CLICK_TO_CALL','ABSTRACT_BANNER_LARGE','ABSTRACT_BANNER_SMALL','ABSTRACT_BANNER_LARGE_CC','ABSTRACT_BANNER_LARGE_CM','ABSTRACT_BANNER_SMALL_CM','ABSTRACT_BANNER_SMALL_CC','FB-LOCAL-AWARENESS','REAL_ESTATE_PROFESSIONAL_CAMPAIGN','RICH_MEDIA_INTERSTITIAL','FB-MOBILE-APP-INSTALLS','FB-PROMOTE-EVENT','FB-INSTAGRAM-VIDEO','FB-INSTAGRAM','DISPLAY_YAHOO','VIDEO_YAHOO','APP_INSTALL_YAHOO','FB-LEAD','DIALOG_CLICK_TO_CALL','YAHOO_CAROUSEL','THIRD-PARTY-AD-TRACK','RICH_MEDIA_SURVEY') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
INSERT INTO `v2_map_user_network` (`id`, `user_id`, `network_id`, `campaign_type`) VALUES (NULL, '32', '1', 'RICH_MEDIA_SURVEY');
ALTER TABLE `users` ADD `is_rich_media_survey` ENUM('Y','N') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT 'Y' AFTER `is_adtrack`;
ALTER TABLE `v2_ads` ADD `rm_question` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `action_buttons`, ADD `rm_answere1` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `rm_question`, ADD `rm_answere2` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `rm_answere1`, ADD `rm_answere3` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `rm_answere2`, ADD `rm_answere4` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `rm_answere3`, ADD `rm_answere5` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `rm_answere4`;
ALTER TABLE `v2_ads` ADD `rm_container` TEXT NULL DEFAULT NULL AFTER `rm_answere5`;
